#!/bin/zsh
#PBS -l nodes=1:ppn=1
#PBS -m ae -M pankov.alex@gmail.com
#PBS -N srna_cutadapt5
#PBS -t 1-4


cd /home/apankov/ilf2_julia/srnaseq/fq_files

f1=($(cat ../samples.txt))
SAMPLE="${f1[$PBS_ARRAYID]}"

~/bin/python /costellolab/shared/software/cutadapt-1.7.1/bin/cutadapt -m 14 -O 5 -g "GTTCAGAGTTCTACAGTCCGACGATC" -o "${SAMPLE}_noAdap_noArchAdap3_5.fastq.gz" "${SAMPLE}_noAdap_noArchAdap.fastq.gz"

