#!/bin/zsh
#PBS -l nodes=1:ppn=1
#PBS -m ae -M pankov.alex@gmail.com
#PBS -N srna_cutadapt
#PBS -t 1-4


cd /home/apankov/ilf2_julia/srnaseq/fq_files

f1=($(cat ../samples.txt))
SAMPLE="${f1[$PBS_ARRAYID]}"

f2=($(cat ../adaps_rc.txt))
adap="${f2[$PBS_ARRAYID]}"

READ="${SAMPLE}.fastq.gz"

~/bin/python /costellolab/shared/software/cutadapt-1.7.1/bin/cutadapt -q 3 -m 14 -O 5 -a "${adap}" -o "${SAMPLE}_noAdap.fastq.gz" "${READ}"


