#!/bin/zsh
#PBS -l nodes=1:ppn=1
#PBS -m ae -M pankov.alex@gmail.com
#PBS -N srna_cutadapt_arch_clean
#PBS -t 1-4


cd /home/apankov/ilf2_julia/srnaseq/fq_files

f1=($(cat ../samples.txt))
SAMPLE="${f1[$PBS_ARRAYID]}"

~/bin/python /costellolab/shared/software/cutadapt-1.7.1/bin/cutadapt -q 3 -m 14 -O 5 --discard-trimmed -a file:arch_adaps.fa -o "${SAMPLE}_noAdap_noArchAdap.fastq.gz" "${SAMPLE}_noAdap.fastq.gz" > "${SAMPLE}_archAdap.log"


